- name: Python
  version: 3.9.1  
  id: 1  
  url: https://www.python.org/ftp/python/3.9.1/python-3.9.1-amd64.exe
  args: -passive

- name: Python 
  version: 3.8.7
  id: 2
  url: https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe
  args: -passive

- name: Everything
  version: 1.3.4.686
  id: 3
  url: https://www.voidtools.com/Everything-1.3.4.686.x64-Setup.exe
  args: /S