- name: Python
  releases:
      - version: 3.9.1
        url: https://www.python.org/ftp/python/3.9.1/python-3.9.1-amd64.exe
        args: -passive

      - version: 3.8.7
        url: https://www.python.org/ftp/python/3.8.7/python-3.8.7-amd64.exe
        args: -passive

- name: Everything
  releases:
      - version: 1.3.4.686
        url: https://www.voidtools.com/Everything-1.3.4.686.x64-Setup.exe
        args: /S