name: Build & Publish

on:
  push:
    paths-ignore: 
        - .github/workflows/*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Droplex
        path: Output/Release/
    
    - name: Publish NuGet Package
      if: ${{ env.PUSH_PACKAGES }}
      run: echo publishing #dotnet nuget push nupkgs\*.nupkg
