name: Build & Publish

on:
  push:
  workflow_dispatch:

jobs:
  workflow:
    runs-on: windows-latest
    env:
      # ${{ env.PUSH_PACKAGES }} when used could potentially be strings "false" or "true"
      PUSH_PACKAGES: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Droplex
        path: Output/Release/
    
    - name: Publish To NuGet 
      if: ${{ github.ref == 'refs/heads/main' }}
      run: nuget push Output\Release\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.PUBLISH}}
    
    - name: Publish To GitHub Releases
      if: $PUSH_PACKAGES #${{ github.ref == 'refs/heads/main' }}
      run: echo "v${{ [System.Diagnostics.FileVersionInfo]::GetVersionInfo("Output\Release\Droplex.dll").ProductVersion }}"
      #uses: softprops/action-gh-release@v1
      #with:
        #files: "WindowWalker*"
        #tag_name: "v${{steps.version.outputs.prop}}"
