name: Build & Publish

on:
  push:
  workflow_dispatch:

jobs:
  workflow:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
   
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Droplex
        path: Output/Release/
    
    - name: Publish To NuGet 
      if: ${{ github.ref == 'refs/heads/main' }}
      run: nuget push Output\Release\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.PUBLISH}}
    
    - name: Get Version
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("Output\Release\Droplex.dll").ProductVersion
        echo "RELEASE_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    
    - name: Publish To GitHub Releases
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v1
      with:
        files: "Output\\Release\\*.nupkg"
        tag_name: "v${{ env.RELEASE_VERSION }}"
